RealTimeNotificationApp/Painel/RealTimeNotificationApp.Painel/Models/AddressModel.cs
namespace RealTimeNotificationApp.Painel.Models
{
    public class AddressModel
    {
        public string Logradouro { get; set; } = string.Empty;
        public string Numero { get; set; } = string.Empty;
        public string Complemento { get; set; } = string.Empty;
        public string Bairro { get; set; } = string.Empty;
        public string CEP { get; set; } = string.Empty;
        public string Municipio { get; set; } = string.Empty;
        public string Uf { get; set; } = string.Empty;
    }
}

RealTimeNotificationApp/Painel/RealTimeNotificationApp.Painel/Models/BrazilianStateModel.cs
namespace RealTimeNotificationApp.Painel.Models
{
    public class BrazilianStateModel
    {
        public string Name { get; set; } = string.Empty;
        public string Abreviation { get; set; } = string.Empty;
    }
}

RealTimeNotificationApp/Painel/RealTimeNotificationApp.Painel/Models/CompleteOrderModel.cs
namespace RealTimeNotificationApp.Painel.Models
{
    public class CompleteOrderModel
    {
        public OrderModel? Pedido { get; set; }
        public DeliveryModel? Entrega { get; set; }
    }
}

RealTimeNotificationApp/Painel/RealTimeNotificationApp.Painel/Models/DeliveryModel.cs
namespace RealTimeNotificationApp.Painel.Models
{
    public class DeliveryModel
    {
        public Guid Id { get; set; }
        public string NumeroPedido { get; set; } = string.Empty;
        public List<DeliveryStatusModel>? ListaStatus { get; set; }
    }
}

RealTimeNotificationApp/Painel/RealTimeNotificationApp.Painel/Models/DeliveryStatusModel.cs
using RealTimeNotificationApp.Painel.Models.Enums;

namespace RealTimeNotificationApp.Painel.Models
{
    public class DeliveryStatusModel(StatusModel status, DateTime dataMovimentacao)
    {
        public StatusModel Status { get; set; } = status;
        public DateTime DataMovimentacao { get; set; } = dataMovimentacao;
    }
}

RealTimeNotificationApp/Painel/RealTimeNotificationApp.Painel/Models/Enums/StatusModel.cs
namespace RealTimeNotificationApp.Painel.Models.Enums
{
    public enum StatusModel
    {
        Registrada = 0,
        PagamentoConfirmado = 1,
        EmSeparacao = 2,
        Iniciada = 3,
        EmRotaDeEntrega = 4,
        Entregue = 5,
        Cancelado = 6
    }
}

RealTimeNotificationApp/Painel/RealTimeNotificationApp.Painel/Models/ErrorViewModel.cs
namespace RealTimeNotificationApp.Painel.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RealTimeNotificationApp/Painel/RealTimeNotificationApp.Painel/Models/OrderModel.cs
namespace RealTimeNotificationApp.Painel.Models
{
    public class OrderModel
    {
        public Guid Id { get; set; }
        public string NumeroPedido { get; set; } = string.Empty;
        public string NomeDestinatario { get; set; } = string.Empty;
        public string Descricao { get; set; } = string.Empty;
        public decimal Valor { get; set; }
        public string Telefone { get; set; } = string.Empty;
        public AddressModel? Endereco { get; set; }
        public DateTime CriadoEm { get; set; } = DateTime.Now;
    }
}

RealTimeNotificationApp/Painel/RealTimeNotificationApp.Painel/Models/UpdateStatusModel.cs
namespace RealTimeNotificationApp.Painel.Models
{
    public class UpdateStatusModel
    {
        public string NumeroPedido { get; set; } = string.Empty;
        public int StatusFinal { get; set; }
    }
}

RealTimeNotificationApp/Painel/RealTimeNotificationApp.Painel/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RealTimeNotificationApp.Painel.Models;
using System.Diagnostics;

namespace RealTimeNotificationApp.Painel.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RealTimeNotificationApp/Painel/RealTimeNotificationApp.Painel/Controllers/PainelController.cs
using Microsoft.AspNetCore.Mvc;

namespace RealTimeNotificationApp.Painel.Controllers
{
    public class PainelController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult NovoStatus()
        {
            return View("Index");
        }

        public IActionResult NovoRegistro() 
        {
            return View();
        }
    }
}

RealTimeNotificationApp/Painel/RealTimeNotificationApp.Painel/Controllers/PedidoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RealTimeNotificationApp.Painel.Models;
using RealTimeNotificationApp.Painel.Services;
using RealTimeNotificationApp.Painel.Services.Interfaces;

namespace RealTimeNotificationApp.Painel.Controllers
{
    public class PedidoController : Controller
    {
        private readonly IApiService _apiService;

        public PedidoController(IApiService apiService)
        {
            _apiService = apiService;
        }

        [HttpGet]
        public IActionResult ConsultarPedido()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ConsultarPedido(string orderNumber)
        {
            if (ModelState.IsValid)
            {
                if (orderNumber == null) { return NotFound(); }

                CompleteOrderModel model = await _apiService.GetCompleteOrder(orderNumber);

                if(model.Entrega == null || model.Pedido == null) { return View(); }
                
                return View(model);
            }

            return View();
        }

        [HttpGet]
        public IActionResult CadastrarPedido()
        {
            CarregarListaUFs();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CadastrarPedido(OrderModel model)
        {
            CarregarListaUFs();

            if (ModelState.IsValid)
            {
                if (model == null) { return View(); }

                CompleteOrderModel result = await _apiService.CreateOrder(model);

                if (result.Pedido == null || result.Entrega == null) { return View(); }

                return RedirectToAction(nameof(Index), "Home");
            }
            return View();
        }

        [HttpGet]
        public IActionResult AlterarStatus()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AlterarStatus(UpdateStatusModel model)
        {
            if (ModelState.IsValid)
            {
                if (model == null) { return View(); }

                var result = await _apiService.UpdateStatus(model);

                if (result) { return RedirectToAction(nameof(Index), "Home"); }

                return View();
            }
            return View();
        }

        private void CarregarListaUFs()
        {
            ViewBag.Estados = BrazilianStatesService.GetEstados().Select(c => new SelectListItem()
            { Text = c.Name, Value = c.Abreviation }).ToList();
        }
    }
}

RealTimeNotificationApp/Painel/RealTimeNotificationApp.Painel/Views/Home/About.cshtml
@{
    ViewData["Title"] = "Sobre";
}

<div class="container">
    <h2>Mais Informações</h2>
    <hr />
    <h5 class="display-5">Informações técnicas</h5>
    <p>Sistema de gerenciamento de pedidos e notificações em tempo real</p>
    <content>
        <p>Ferramentas usadas:</p>
        <ul>
            <li>Api desenvolvida em .NET Core versão 8</li>
            <li>Front desenvolvido um Asp Net Core MVC</li>
            <li>Linguagens: C# e Html</li>
            <li>Banco de dados: Banco não relacional MongoDB</li>
            <li>Biblioteca SignalR para as notificações em tempo real</li>
        </ul>
    </content>
    <p>Veja mais no <a href="https://github.com/EmmanuelEgitoBr/PainelNotificacoes" target="_blank">Repositório do Github</a>.</p>
</div>

RealTimeNotificationApp/Painel/RealTimeNotificationApp.Painel/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo</h1>
    <p>Esse sistema permite o gerenciamento de pedidos, bem como acompanhar mudanças em tempo real</p>
</div>
<hr />
<div class="container">
    <ul>
        <li>
            Para acompanhamento de notificações de alterações de status de pedido, clique no link abaixo:
            <a class="nav-link text-primary" asp-area="" asp-controller="Painel" asp-action="NovoStatus"><b>Notificações de mudança de status</b></a>
        </li>
        <li>
            Para acompanhamento de notificações de novo registro de pedido, clique no link abaixo:
            <a class="nav-link text-primary" asp-area="" asp-controller="Painel" asp-action="NovoRegistro"><b>Notificações de criação de pedido</b></a>
        </li>
        <li>
            Para consulta completa de um determinado pedido, clique no link abaixo:
            <a class="nav-link text-primary" asp-area="" asp-controller="Pedido" asp-action="ConsultarPedido"><b>Consulte um pedido</b></a>
        </li>
        <li>Para cadastro de novo pedido, clique no link abaixo: 
            <a class="nav-link text-primary" asp-area="" asp-controller="Pedido" asp-action="CadastrarPedido"><b>Cadastre um pedido</b></a>
        </li>
        <li>
            Para alterar status de um pedido, clique no link abaixo:
            <a class="nav-link text-primary" asp-area="" asp-controller="Pedido" asp-action="AlterarStatus"><b>Atualize o status do pedido</b></a>
        </li>
    </ul>
</div>
<hr />

RealTimeNotificationApp/Painel/RealTimeNotificationApp.Painel/Views/Painel/Index.cshtml
@{
    ViewData["Title"] = "Status";
}

<div class="container">
    <h3>Painel de Notificações</h3>
    <hr />
    <h5>Notificações de mudança de status de pedido</h5>
    <br />
    <div class="container">
        <ul>
            <li id="orders"></li>
        </ul>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/7.0.0/signalr.min.js"></script>
    <script>
        // Conecta ao Hub
        const connection = new signalR.HubConnectionBuilder()
            .withUrl("https://localhost:7230/orderHub", {
                withCredentials: false
            })
            .withAutomaticReconnect()
            .configureLogging(signalR.LogLevel.Information)
            .build();

        // Atualiza o painel quando receber uma nova atualização
        connection.on("ReceiveOrderStatusUpdate", (orderNumber, status) => {
            const ordersDiv = document.getElementById("orders");
            const orderElement = document.getElementById(orderNumber);
            var statusName = "";
            switch (status) {
                case 0:
                    statusName = "Registrada";
                    break;
                case 1:
                    statusName = "Pagamento confirmado";
                    break;
                case 2:
                    statusName = "Em separação";
                    break;
                case 3:
                    statusName = "Iniciada";
                    break;
                case 4:
                    statusName = "Em rota de entrega";
                    break;
                case 5:
                    statusName = "Entregue";
                    break;
                case 6:
                    statusName = "Cancelado";
            }
            let now = new Date().toLocaleDateString();
            let displayMessage = `Número do pedido: ${orderNumber} --- Novo Status: ${statusName} --- Data: ${now}`;

            if (orderElement) {
                // Atualiza o status do pedido
                orderElement.innerText = displayMessage;
            } else {
                // Cria um novo elemento para o pedido
                const newOrder = document.createElement("div");
                newOrder.id = orderNumber;
                newOrder.innerText = displayMessage;
                ordersDiv.appendChild(newOrder);
            }
        });

        // Inicia a conexão
        connection.start().catch(err => console.error(err));
    </script>
</div>

RealTimeNotificationApp/Painel/RealTimeNotificationApp.Painel/Views/Painel/NovoRegistro.cshtml
@{
    ViewData["Title"] = "Registro";
}

<div class="container">
    <h3>Painel de Notificações</h3>
    <hr />
    <h5>Notificações de criação de novo pedido</h5>
    <br />
    <div class="container">
        <ul>
            <li id="orders"></li>
        </ul>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/7.0.0/signalr.min.js"></script>
    <script>
        // Conecta ao Hub
        const connection = new signalR.HubConnectionBuilder()
            .withUrl("https://localhost:7230/orderHub", {
                withCredentials: false
            })
            .withAutomaticReconnect()
            .configureLogging(signalR.LogLevel.Information)
            .build();

        // Atualiza o painel quando receber uma nova atualização
        connection.on("ReceiveCreationNewOrder", (orderNumber) => {
            const ordersDiv = document.getElementById("orders");
            const orderElement = document.getElementById(orderNumber);
            let now = new Date().toLocaleDateString();

            const newOrder = document.createElement("div");
            newOrder.id = orderNumber;
            newOrder.innerText = `Número do pedido: ${orderNumber} --- Data: ${now}`;
            ordersDiv.appendChild(newOrder);
        });

        // Inicia a conexão
        connection.start().catch(err => console.error(err));
    </script>
</div>

RealTimeNotificationApp/Painel/RealTimeNotificationApp.Painel/Views/Pedido/AlterarStatus.cshtml
@{
    ViewData["Title"] = "Alterar Status";
}
@model UpdateStatusModel

<div class="container">
    <h3>Alterar Status de Entrega de Pedido</h3>
    <hr />
    <form asp-action="AlterarStatus">
        <div class="form-horizontal">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Número do pedido:</label>
                        <div>
                            <input asp-for="NumeroPedido" class="form-control" />
                            <span asp-validation-for="NumeroPedido" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Selecione novo Status:</label>
                        <div>
                            <select asp-for="StatusFinal" class="form-control">
                                <option selected value="0">Registrada</option>
                                <option value="1">Pagamento Confirmado</option>
                                <option value="2">Em Separação</option>
                                <option value="3">Iniciada</option>
                                <option value="4">Em Rota De Entrega</option>
                                <option value="5">Entregue</option>
                                <option value="6">Cancelado</option>
                            </select>
                            <span asp-validation-for="StatusFinal" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <hr />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Alterar" class="btn btn-success" />
                    <a asp-controller="Home" asp-action="Index" class="btn btn-info">Voltar para início</a>
                </div>
            </div>
        </div>
    </form>
</div>

RealTimeNotificationApp/Painel/RealTimeNotificationApp.Painel/Views/Pedido/CadastrarPedido.cshtml
@{
    ViewData["Title"] = "Cadastro";
}
@model OrderModel

<div class="container">
    <h3>Cadastrar novo pedido</h3>
    <hr />
    <form asp-action="CadastrarPedido">
        <div class="form-horizontal">
            <div asp-validation-summary="All" class="text-danger"></div>
            <h5>Informações gerais</h5>
            <br />
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Nome do destinatário:</label>
                        <div>
                            <input asp-for="NomeDestinatario" class="form-control" />
                            <span asp-validation-for="NomeDestinatario" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Descrição do pedido:</label>
                        <div>
                            <input asp-for="Descricao" class="form-control" />
                            <span asp-validation-for="Descricao" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Valor total do pedido:</label>
                        <div>
                            <input asp-for="Valor" class="form-control" />
                            <span asp-validation-for="Valor" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Telefone de contato:</label>
                        <div>
                            <input asp-for="Telefone" class="form-control" />
                            <span asp-validation-for="Telefone" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <br />
            <h5>Endereço de entrega</h5>
            <br />
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="control-label">Logradouro:</label>
                        <div>
                            <input asp-for="Endereco!.Logradouro" class="form-control" />
                            <span asp-validation-for="Endereco!.Logradouro" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="control-label">Número:</label>
                        <div>
                            <input asp-for="Endereco!.Numero" class="form-control" />
                            <span asp-validation-for="Endereco!.Numero" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="control-label">Complemento:</label>
                        <div>
                            <input asp-for="Endereco!.Complemento" class="form-control" />
                            <span asp-validation-for="Endereco!.Complemento" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="control-label">Bairro:</label>
                        <div>
                            <input asp-for="Endereco!.Bairro" class="form-control" />
                            <span asp-validation-for="Endereco!.Bairro" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="control-label">CEP:</label>
                        <div>
                            <input asp-for="Endereco!.CEP" class="form-control" />
                            <span asp-validation-for="Endereco!.CEP" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="control-label">Município:</label>
                        <div>
                            <input asp-for="Endereco!.Municipio" class="form-control" />
                            <span asp-validation-for="Endereco!.Municipio" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="control-label">UF:</label>
                        <div>
                            <select asp-for="Endereco!.Uf" asp-items="@ViewBag.Estados" class="form-control">
                            </select>
                            <span asp-validation-for="Endereco!.Uf" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <hr />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Cadastrar" class="btn btn-success" />
                    <a asp-controller="Home" asp-action="Index" class="btn btn-info">Voltar para início</a>
                </div>
            </div>
        </div>
    </form>
</div>

RealTimeNotificationApp/Painel/RealTimeNotificationApp.Painel/Views/Pedido/ConsultarPedido.cshtml
@{
    ViewData["Title"] = "Consulta";
}
@model CompleteOrderModel

<div style="padding:15px">
    <h3>Consulta de pedido</h3>
</div>
<div style="padding:5px">
    <h5>Faça a consulta pelo número do pedido</h5>
</div>
<form asp-action="ConsultarPedido" method="post">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <label class="form-label" for="orderNumber">Insira o número do pedido:</label>
            </div>
            <div class="col-md-3">
                <input class="form-control" type="text" id="orderNumber" name="orderNumber" asp-for="Pedido!.NumeroPedido" />
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button class=" btn btn-primary" type="submit">Consultar</button>
            <a asp-controller="Home" asp-action="Index" class="btn btn-info">Voltar para início</a>
        </div>
    </div>
</form>
<hr />
@if (Model != null)
{
    <div class="container">
        <h5>Informações do pedido</h5>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <b><label class="form-label">Nº do pedido:</label></b>
            </div>
            <div class="col-md-3">
                <b><label class="form-label">Destinatário:</label></b>
            </div>
            <div class="col-md-3">
                <b><label class="form-label">Descrição:</label></b>
            </div>
            <div class="col-md-3">
                <b><label class="form-label">Valor Total:</label></b>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <label style="font-size:small">@Html.DisplayFor(model => model.Entrega!.NumeroPedido)</label>
            </div>
            <div class="col-md-3">
                <label style="font-size:small">@Html.DisplayFor(model => model.Pedido!.NomeDestinatario)</label>
            </div>
            <div class="col-md-3">
                <label style="font-size:small">@Html.DisplayFor(model => model.Pedido!.Descricao)</label>
            </div>
            <div class="col-md-3">
                <label>R$ @Html.DisplayFor(model => model.Pedido!.Valor)</label>
            </div>
        </div>
        <div style="height:10px"></div>
        <div class="row">
            <div class="col-md-3">
                <b><label class="form-label">Telefone:</label></b>
            </div>
            <div class="col-md-3">
                <b><label class="form-label">Data Registro:</label></b>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <label>@Html.DisplayFor(model => model.Pedido!.Telefone)</label>
            </div>
            <div class="col-md-3">
                <label style="font-size:small">@Html.DisplayFor(model => model.Pedido!.CriadoEm)</label>
            </div>
        </div>
        <hr />
        <div >
            <h5>Endereço</h5>
        </div>
        <div class="row">
            <div class="col-md-3">
                <b><label class="form-label">Logradouro:</label></b>
            </div>
            <div class="col-md-3">
                <b><label class="form-label">Número:</label></b>
            </div>
            <div class="col-md-3">
                <b><label class="form-label">Complemento:</label></b>
            </div>
            <div class="col-md-3">
                <b><label class="form-label">Bairro:</label></b>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <label>@Html.DisplayFor(model => model.Pedido!.Endereco!.Logradouro)</label>
            </div>
            <div class="col-md-3">
                <label style="font-size:small">@Html.DisplayFor(model => model.Pedido!.Endereco!.Numero)</label>
            </div>
            <div class="col-md-3">
                <label>@Html.DisplayFor(model => model.Pedido!.Endereco!.Complemento)</label>
            </div>
            <div class="col-md-3">
                <label>@Html.DisplayFor(model => model.Pedido!.Endereco!.Bairro)</label>
            </div>
        </div>
        <div style="height:10px"></div>
        <div class="row">
            <div class="col-md-3">
                <b><label class="form-label">CEP:</label></b>
            </div>
            <div class="col-md-3">
                <b><label class="form-label">Município:</label></b>
            </div>
            <div class="col-md-3">
                <b><label class="form-label">UF:</label></b>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <label>@Html.DisplayFor(model => model.Pedido!.Endereco!.CEP)</label>
            </div>
            <div class="col-md-3">
                <label style="font-size:small">@Html.DisplayFor(model => model.Pedido!.Endereco!.Municipio)</label>
            </div>
            <div class="col-md-3">
                <label style="font-size:small">@Html.DisplayFor(model => model.Pedido!.Endereco!.Uf)</label>
            </div>
        </div>
    </div>
    <hr />
    <div class="container">
        <h5>Histórico de Status</h5>
    </div>
    <div class="container">
        <div>
            @foreach (var item in Model.Entrega.ListaStatus)
            {
                <div class="row">
                    <div class="col-md-3">
                        <b><label class="form-label">Status:</label></b>
                    </div>
                    <div class="col-md-3">
                        <b><label class="form-label">Data Movimentação:</label></b>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <label>@Html.DisplayFor(modelItem => item.Status)</label>
                    </div>
                    <div class="col-md-3">
                        <label style="font-size:small">@Html.DisplayFor(modelItem => item.DataMovimentacao)</label>
                    </div>
                </div>
            }
        </div>
    </div>
}

RealTimeNotificationApp/Painel/RealTimeNotificationApp.Painel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gestão de pedidos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RealTimeNotificationApp.Painel.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gerenciamento de Pedidos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Início</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">Sobre</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Gerenciamento de Pedidos
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>